// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var ImportJsValueGen = require("./ImportJsValue.gen");

var $$default = ImportJsValueGen.default;

exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* default Not a pure module */
